name: Sync upstream Saleor Apps repository
on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: saleor/apps
          test_mode: ${{ inputs.sync_test_mode }}
          upstream_pull_args: '--tags'
          target_branch_push_args: '--tags'

